#pragma once

#include <d3d9.h>

typedef enum 
{
    TEXTURE_INDEX_YUKIDARUMA,
	TEXTURE_INDEX_ZOMBIE,
	TEXTURE_INDEX_BULLET,
	TEXTURE_INDEX_LASER,
	TEXTURE_INDEX_EXPLOSION,
	TEXTURE_INDEX_NUMBER,
	TEXTURE_INDEX_TITLE,
	TEXTURE_INDEX_ENEMY,

	TEXTURE_INDEX_STAGE_START,
	TEXTURE_INDEX_STAGE1,
	TEXTURE_INDEX_STAGE2,
	TEXTURE_INDEX_STAGE3,
	TEXTURE_INDEX_STAGE_END,

	TEXTURE_INDEX_BGMAIN,
	TEXTURE_INDEX_BGLOOP,

	TEXTURE_INDEX_RESULT,
	TEXTURE_INDEX_TILEMAP,
	TEXTURE_INDEX_CIRCLE,
	TEXTURE_INDEX_EXPLOSION2,
	TEXTURE_INDEX_EXPLOSION3,
	TEXTURE_INDEX_JOUGAI,
	TEXTURE_INDEX_ATTACK_SPEED,
	TEXTURE_INDEX_PLAYER,
	TEXTURE_INDEX_NUMBER3,
	TEXTURE_INDEX_PUSH,
	TEXTURE_INDEX_TAI,
	TEXTURE_INDEX_SOU,
	TEXTURE_INDEX_HPSITA,
	TEXTURE_INDEX_HPUE,
	TEXTURE_INDEX_TISIBUKI,
	TEXTURE_INDEX_HIT,
	TEXTURE_INDEX_CONTROLLER,
	TEXTURE_INDEX_CREATE,
	TEXTURE_INDEX_DELETE,
	TEXTURE_INDEX_HINT,
	TEXTURE_INDEX_AOZOMBIE,
	TEXTURE_INDEX_GAMEOVER,
	TEXTURE_INDEX_DOWNHIT,

    TEXTURE_INDEX_MAX
}TextureIndex;

int Texture_Load(void); //èâä˙âª
void Texture_Release(void); //èIóπèàóù
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);
int Texture_GetWidth(TextureIndex index);
int Texture_GetHeight(TextureIndex index);
